// Code generated by templ - DO NOT EDIT.

package email

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"bytes"
	"context"
)

type ResetPassword struct {
	ResetURL string
}

var _ Transformer = (*ResetPassword)(nil)

func (r ResetPassword) ToHTML() (string, error) {
	var buf bytes.Buffer
	if err := r.render().Render(context.Background(), &buf); err != nil {
		return "", err
	}

	return buf.String(), nil
}

func (r ResetPassword) ToText() (string, error) {
	html, err := r.ToHTML()
	if err != nil {
		return "", err
	}

	return HTMLToText(html)
}

func (r ResetPassword) render() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" style=\"width: 100%;\"><tbody><tr><td class=\"andurel-email-max-sm-px-6 andurel-email-max-sm-pt-8\" style=\"padding-inline: 48px; padding-top: 48px; padding-bottom: 20px;\"><p style=\"margin: 0; margin-bottom: 12px; font-family: Arial,sans-serif; font-size: 12px; line-height: 16px; font-weight: 700; letter-spacing: 0.12em; color: #ff6b1a; text-transform: uppercase;\">Password assistance</p><h1 class=\"andurel-email-max-sm-text-2xl andurel-email-max-sm-leading-8\" style=\"margin: 0; font-family: Arial,sans-serif; font-size: 30px; line-height: 38px; font-weight: 700; color: #172033;\">Reset your password</h1></td></tr><tr><td class=\"andurel-email-max-sm-px-6\" style=\"padding-inline: 48px; padding-bottom: 24px; font-family: Arial,sans-serif; font-size: 16px; line-height: 24px; color: #172033;\"><p style=\"margin: 0;\">Hi,</p><p style=\"margin: 0; margin-top: 16px;\">We received a request to reset your password. Use the button below to choose a new one.</p></td></tr><tr><td class=\"andurel-email-max-sm-px-6\" style=\"padding-inline: 48px; padding-bottom: 24px;\"><table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr><td align=\"center\" style=\"border-radius: 0; background-color: #ff6b1a; text-align: center;\" bgcolor=\"#ff6b1a\"><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 templ.SafeURL
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinURLErrs(r.ResetURL)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `email/reset_password.templ`, Line: 60, Col: 30}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"andurel-email-hover-bg-primary\" style=\"display: block; padding-inline: 24px; padding-block: 12px; font-family: Arial,sans-serif; font-size: 16px; line-height: 24px; font-weight: 700; color: #130f0b; text-decoration-line: none;\">Reset my password</a></td></tr></tbody></table></td></tr><tr><td class=\"andurel-email-max-sm-px-6\" style=\"padding-inline: 48px; padding-bottom: 24px; font-family: Arial,sans-serif; font-size: 14px; line-height: 24px; color: #687385;\"><p style=\"margin: 0;\">If the button does not work, copy this URL into your browser:</p><p style=\"margin: 0; margin-top: 8px; word-break: break-all; color: #ff6b1a;\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(r.ResetURL)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `email/reset_password.templ`, Line: 72, Col: 61}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p></td></tr><tr><td class=\"andurel-email-max-sm-px-6\" style=\"padding-inline: 48px; padding-bottom: 16px; font-family: Arial,sans-serif; font-size: 14px; line-height: 24px; color: #687385;\"><p style=\"margin: 0;\">This link expires in one hour.</p><p style=\"margin: 0; margin-top: 16px;\">If you did not request a password reset, you can safely ignore this email.</p></td></tr></tbody></table>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = baseLayout("Reset Your Password", "Reset your password using the secure link in this email.").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
