// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package email

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"bytes"
	"context"
)

type ResetPassword struct {
	ResetURL string
}

var _ Transformer = (*ResetPassword)(nil)

func (r ResetPassword) ToHTML() (string, error) {
	var buf bytes.Buffer
	if err := r.render().Render(context.Background(), &buf); err != nil {
		return "", err
	}

	return buf.String(), nil
}

func (r ResetPassword) ToText() (string, error) {
	html, err := r.ToHTML()
	if err != nil {
		return "", err
	}

	return HTMLToText(html)
}

func (r ResetPassword) render() templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\" width=\"100%\" class=\"w-full\"><tbody><tr><td class=\"px-12 pt-12 pb-5 max-sm:px-6 max-sm:pt-8\"><p class=\"m-0 mb-3 [font-family:Arial,sans-serif] text-xs leading-4 font-bold tracking-[0.12em] text-[#625afa] uppercase\">Password assistance</p><h1 class=\"m-0 [font-family:Arial,sans-serif] text-[30px] leading-[38px] font-bold text-[#172033] max-sm:text-2xl max-sm:leading-8\">Reset your password</h1></td></tr><tr><td class=\"px-12 pb-6 [font-family:Arial,sans-serif] text-base leading-6 text-[#414552] max-sm:px-6\"><p class=\"m-0\">Hi,</p><p class=\"m-0 mt-4\">We received a request to reset your password. Use the button below to choose a new one.</p></td></tr><tr><td class=\"px-12 pb-6 max-sm:px-6\"><table role=\"presentation\" border=\"0\" cellpadding=\"0\" cellspacing=\"0\"><tbody><tr><td align=\"center\" class=\"rounded-md bg-[#625afa] text-center\"><a href=\"")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 templ.SafeURL
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinURLErrs(r.ResetURL)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `email/reset_password.templ`, Line: 60, Col: 30}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\" class=\"block px-6 py-3 [font-family:Arial,sans-serif] text-base leading-6 font-bold text-white no-underline hover:bg-[#4f46e5]\">Reset my password</a></td></tr></tbody></table></td></tr><tr><td class=\"px-12 pb-6 [font-family:Arial,sans-serif] text-sm leading-6 text-[#687385] max-sm:px-6\"><p class=\"m-0\">If the button does not work, copy this URL into your browser:</p><p class=\"m-0 mt-2 break-all text-[#625afa]\">")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var4 string
			templ_7745c5c3_Var4, templ_7745c5c3_Err = templ.JoinStringErrs(r.ResetURL)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `email/reset_password.templ`, Line: 72, Col: 63}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var4))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</p></td></tr><tr><td class=\"px-12 pb-4 [font-family:Arial,sans-serif] text-sm leading-6 text-[#687385] max-sm:px-6\"><p class=\"m-0\">This link expires in one hour.</p><p class=\"m-0 mt-4\">If you did not request a password reset, you can safely ignore this email.</p></td></tr></tbody></table>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = baseLayout("Reset Your Password", "Reset your password using the secure link in this email.").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
