schemaVersion = 1
version = 'v2.0.0-alpha'

[project]
  name = 'andurel-site'
  inertia = 'react'
  javascriptPackageManager = 'pnpm'
  javascriptSSRRuntime = 'node'

[database]
  engine = 'postgresql'
  nullType = 'pgtype.Null'

[tools]
  dblab = 'v0.40.2'
  goose = 'v3.27.1'
  mailpit = 'v1.30.2'
  narsilc = 'v0.4.4'
  shadowfax = 'v0.12.0'
  tailwindcli = 'v4.3.2'
  templ = 'v0.3.1020'
  usql = 'v0.21.4'
