// Code generated by andurel; DO NOT EDIT.

type HostOrigins = Record<string, string>

let origins: HostOrigins = {}

/** Call once at boot with Inertia shared hosts prop. */
export function configureRouteHosts(next: HostOrigins) {
  origins = next
}

function origin(host: string): string {
  return origins[host] ?? origins.primary ?? ''
}

export const routes = {
  adminApiTokenCreate: routeHelper({
    host: 'admin',
    path: () => '/tokens',
  }),
  adminApiTokenDestroy: routeHelper({
    host: 'admin',
    path: (id: string) => `/tokens/${id}`,
  }),
  adminApiTokenIndex: routeHelper({
    host: 'admin',
    path: () => '/tokens',
  }),
  adminApiTokenNew: routeHelper({
    host: 'admin',
    path: () => '/tokens/new',
  }),
  adminApiTokenShow: routeHelper({
    host: 'admin',
    path: (id: string) => `/tokens/${id}`,
  }),
  adminApiTokenUpdate: routeHelper({
    host: 'admin',
    path: (id: string) => `/tokens/${id}`,
  }),
  adminDashboardHome: routeHelper({
    host: 'admin',
    path: () => '/',
  }),
  adminDocumentationPagePreview: routeHelper({
    host: 'admin',
    path: (id: number) => `/docs/pages/${id}/preview`,
  }),
  adminDocumentationPagePublish: routeHelper({
    host: 'admin',
    path: (id: number) => `/docs/pages/${id}/publish`,
  }),
  adminDocumentationPageRestore: routeHelper({
    host: 'admin',
    path: (id: string, revisionId: string) => `/docs/pages/${id}/revisions/${revisionId}/restore`,
  }),
  adminDocumentationPageShow: routeHelper({
    host: 'admin',
    path: (id: number) => `/docs/pages/${id}`,
  }),
  adminDocumentationPageUpdate: routeHelper({
    host: 'admin',
    path: (id: number) => `/docs/pages/${id}`,
  }),
  adminDocumentationVersionCreate: routeHelper({
    host: 'admin',
    path: () => '/docs',
  }),
  adminDocumentationVersionCreatePage: routeHelper({
    host: 'admin',
    path: (id: number) => `/docs/${id}/pages`,
  }),
  adminDocumentationVersionIndex: routeHelper({
    host: 'admin',
    path: () => '/docs',
  }),
  adminDocumentationVersionNew: routeHelper({
    host: 'admin',
    path: () => '/docs/new',
  }),
  adminDocumentationVersionPublishNav: routeHelper({
    host: 'admin',
    path: (id: number) => `/docs/${id}/nav/publish`,
  }),
  adminDocumentationVersionShow: routeHelper({
    host: 'admin',
    path: (id: number) => `/docs/${id}`,
  }),
  adminDocumentationVersionUpdate: routeHelper({
    host: 'admin',
    path: (id: number) => `/docs/${id}`,
  }),
  adminDocumentationVersionUpdateNav: routeHelper({
    host: 'admin',
    path: (id: number) => `/docs/${id}/nav`,
  }),
  confirmationCreate: routeHelper({
    host: 'primary',
    path: () => '/users/confirmation',
  }),
  confirmationNew: routeHelper({
    host: 'primary',
    path: () => '/users/confirmation/new',
  }),
  documentationShow: routeHelper({
    host: 'primary',
    path: (version: string, slug: string) => `/docs/${version}/${slug}`,
  }),
  homePage: routeHelper({
    host: 'primary',
    path: () => '/',
  }),
  passwordCreate: routeHelper({
    host: 'primary',
    path: () => '/users/password',
  }),
  passwordEdit: routeHelper({
    host: 'primary',
    path: (token: string) => `/users/password/${token}/edit`,
  }),
  passwordNew: routeHelper({
    host: 'primary',
    path: () => '/users/password/new',
  }),
  passwordUpdate: routeHelper({
    host: 'primary',
    path: () => '/users/password',
  }),
  registrationCreate: routeHelper({
    host: 'primary',
    path: () => '/users',
  }),
  registrationNew: routeHelper({
    host: 'primary',
    path: () => '/users/sign-up',
  }),
  sessionCreate: routeHelper({
    host: 'admin',
    path: () => '/users/sign-in',
  }),
  sessionDestroy: routeHelper({
    host: 'admin',
    path: () => '/users/sign-out',
  }),
  sessionNew: routeHelper({
    host: 'admin',
    path: () => '/users/sign-in',
  }),
}

function routeHelper<Args extends unknown[]>(def: {
  host: string
  path: (...args: Args) => string
}) {
  const full = (...args: Args) => origin(def.host) + def.path(...args)
  return Object.assign(full, {
    path: def.path,
    host: def.host,
  })
}
