// Code generated by andurel; DO NOT EDIT.

type HostOrigins = Record<string, string>

let origins: HostOrigins = {}

/** Call once at boot with Inertia shared hosts prop. */
export function configureRouteHosts(next: HostOrigins) {
  origins = next
}

function origin(host: string): string {
  return origins[host] ?? origins.primary ?? ''
}

export const routes = {
  confirmationCreate: routeHelper({
    host: 'primary',
    path: () => '/users/confirmation',
  }),
  confirmationNew: routeHelper({
    host: 'primary',
    path: () => '/users/confirmation/new',
  }),
  documentationShow: routeHelper({
    host: 'primary',
    path: (version: string, slug: string) => `/docs/${version}/${slug}`,
  }),
  homePage: routeHelper({
    host: 'primary',
    path: () => '/',
  }),
  passwordCreate: routeHelper({
    host: 'primary',
    path: () => '/users/password',
  }),
  passwordEdit: routeHelper({
    host: 'primary',
    path: (token: string) => `/users/password/${token}/edit`,
  }),
  passwordNew: routeHelper({
    host: 'primary',
    path: () => '/users/password/new',
  }),
  passwordUpdate: routeHelper({
    host: 'primary',
    path: () => '/users/password',
  }),
  registrationCreate: routeHelper({
    host: 'primary',
    path: () => '/users',
  }),
  registrationNew: routeHelper({
    host: 'primary',
    path: () => '/users/sign-up',
  }),
  sessionCreate: routeHelper({
    host: 'primary',
    path: () => '/users/sign-in',
  }),
  sessionDestroy: routeHelper({
    host: 'primary',
    path: () => '/users/sign-out',
  }),
  sessionNew: routeHelper({
    host: 'primary',
    path: () => '/users/sign-in',
  }),
}

function routeHelper<Args extends unknown[]>(def: {
  host: string
  path: (...args: Args) => string
}) {
  const full = (...args: Args) => origin(def.host) + def.path(...args)
  return Object.assign(full, {
    path: def.path,
    host: def.host,
  })
}
