// Code generated by andurel; DO NOT EDIT.

export type ApiTokenData = {
  id: string
  name: string
  tokenPrefix: string
  expiresAt: string
  lastUsedAt: string
  createdAt: string
}

export type ApiTokenIndexProps = {
  tokens: ApiTokenData[]
}

export type ApiTokenItemProps = {
  token: ApiTokenData
  revealedToken: string
}

export type CreateApiTokenFormPayload = {
  name: string
  token: string
  expiresAt: string
}

export type CreateDocumentationPageFormPayload = {
  slug: string
  title: string
}

export type CreateDocumentationVersionFormPayload = {
  slug: string
  label: string
  isLatest: boolean
  position: number
}

export type DocumentationHeadingData = {
  id: string
  text: string
  level: number
}

export type DocumentationNavDraftData = {
  id: number
  status: string
  tree: DocumentationNavNodeData[]
}

export type DocumentationNavNodeData = {
  title: string
  pageId: number | null
  children: DocumentationNavNodeData[]
}

export type DocumentationPageData = {
  id: number
  versionId: number
  slug: string
  publishedRevisionId: number | null
}

export type DocumentationPageItemProps = {
  version: DocumentationVersionData
  page: DocumentationPageData
  draft: DocumentationRevisionData
  published: DocumentationRevisionData | null
  revisions: DocumentationRevisionData[]
}

export type DocumentationPageSummaryData = {
  id: number
  slug: string
  title: string
  hasDraft: boolean
  isPublished: boolean
}

export type DocumentationRevisionData = {
  id: number
  status: string
  title: string
  metaTitle: string
  description: string
  bodyMarkdown: string
  headings: DocumentationHeadingData[]
  createdAt: string
  publishedAt: string
}

export type DocumentationVersionData = {
  id: number
  slug: string
  label: string
  isLatest: boolean
  position: number
  publishedNavId: number | null
  updatedAt: string
}

export type DocumentationVersionIndexProps = {
  versions: DocumentationVersionData[]
}

export type DocumentationVersionItemProps = {
  version: DocumentationVersionData
  pages: DocumentationPageSummaryData[]
  navDraft: DocumentationNavDraftData
}

export type PreviewDocumentationPageFormPayload = {
  bodyMarkdown: string
}

export type UpdateApiTokenFormPayload = {
  name: string
  token: string
  expiresAt: string
}

export type UpdateDocumentationNavFormPayload = {
  tree: DocumentationNavNodeData[]
}

export type UpdateDocumentationPageFormPayload = {
  slug: string
  title: string
  metaTitle: string
  description: string
  bodyMarkdown: string
}

export type UpdateDocumentationVersionFormPayload = {
  slug: string
  label: string
  isLatest: boolean
  position: number
}
