// Code generated by narsilc. DO NOT EDIT.
// source: documentation_version.sql

package queries

import (
	"context"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/mbvlabs/narsilc"
)

const clearDocumentationVersionLatest = `-- name: ClearDocumentationVersionLatest :exec
UPDATE documentation_versions
SET is_latest = false, updated_at = $1
WHERE is_latest = true
`

// Clears the latest flag on every version.
func (q *Queries) ClearDocumentationVersionLatest(ctx context.Context, updatedAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, clearDocumentationVersionLatest, updatedAt)
	return err
}

const countDocumentationVersions = `-- name: CountDocumentationVersions :one
SELECT count(*)
FROM documentation_versions
`

// Counts DocumentationVersion rows.
func (q *Queries) CountDocumentationVersions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentationVersions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocumentationVersion = `-- name: CreateDocumentationVersion :one
INSERT INTO documentation_versions (
	created_at,
	updated_at,
	slug,
	label,
	is_latest,
	position,
	published_nav_id
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7
)
RETURNING id, created_at, updated_at, slug, label, is_latest, position, published_nav_id
`

type CreateDocumentationVersionParams struct {
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Slug           string
	Label          string
	IsLatest       bool
	Position       int32
	PublishedNavID pgtype.Int8
}

// Inserts one DocumentationVersion and returns the row.
func (q *Queries) CreateDocumentationVersion[T any](ctx context.Context, arg CreateDocumentationVersionParams) (T, error) {
	row := q.db.QueryRow(ctx, createDocumentationVersion,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Slug,
		arg.Label,
		arg.IsLatest,
		arg.Position,
		arg.PublishedNavID,
	)
	return narsilc.Scan[T](row, []string{"id", "created_at", "updated_at", "slug", "label", "is_latest", "position", "published_nav_id"})
}

const deleteDocumentationVersion = `-- name: DeleteDocumentationVersion :exec
DELETE FROM documentation_versions
WHERE id = $1
`

// Deletes one DocumentationVersion by primary key.
func (q *Queries) DeleteDocumentationVersion(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDocumentationVersion, id)
	return err
}

const getDocumentationVersion = `-- name: GetDocumentationVersion :one
SELECT id, created_at, updated_at, slug, label, is_latest, position, published_nav_id
FROM documentation_versions
WHERE id = $1
LIMIT 1
`

// Fetches one DocumentationVersion by primary key.
func (q *Queries) GetDocumentationVersion[T any](ctx context.Context, id int64) (T, error) {
	row := q.db.QueryRow(ctx, getDocumentationVersion, id)
	return narsilc.Scan[T](row, []string{"id", "created_at", "updated_at", "slug", "label", "is_latest", "position", "published_nav_id"})
}

const getDocumentationVersionBySlug = `-- name: GetDocumentationVersionBySlug :one
SELECT id, created_at, updated_at, slug, label, is_latest, position, published_nav_id
FROM documentation_versions
WHERE slug = $1
LIMIT 1
`

func (q *Queries) GetDocumentationVersionBySlug[T any](ctx context.Context, slug string) (T, error) {
	row := q.db.QueryRow(ctx, getDocumentationVersionBySlug, slug)
	return narsilc.Scan[T](row, []string{"id", "created_at", "updated_at", "slug", "label", "is_latest", "position", "published_nav_id"})
}

const listDocumentationVersions = `-- name: ListDocumentationVersions :many
SELECT id, created_at, updated_at, slug, label, is_latest, position, published_nav_id
FROM documentation_versions
`

// Lists DocumentationVersion rows.

func (q *Queries) ListDocumentationVersions[T any](ctx context.Context) *ListDocumentationVersionsBuilder[T] {
	return &ListDocumentationVersionsBuilder[T]{
		q:        q,
		ctx:      ctx,
		args:     []any{},
		hasWhere: false,
		dollar:   true,
	}
}

type ListDocumentationVersionsBuilder[T any] struct {
	q        *Queries
	ctx      context.Context
	args     []any
	conds    []string
	order    string
	limit    *int32
	offset   *int32
	hasWhere bool
	dollar   bool
}

func (b *ListDocumentationVersionsBuilder[T]) OrderByIDAsc() *ListDocumentationVersionsBuilder[T] {
	b.order = `id ASC`
	return b
}

func (b *ListDocumentationVersionsBuilder[T]) OrderByIDDesc() *ListDocumentationVersionsBuilder[T] {
	b.order = `id DESC`
	return b
}

func (b *ListDocumentationVersionsBuilder[T]) Limit(n int32) *ListDocumentationVersionsBuilder[T] {
	b.limit = &n
	return b
}

func (b *ListDocumentationVersionsBuilder[T]) Offset(n int32) *ListDocumentationVersionsBuilder[T] {
	b.offset = &n
	return b
}

func (b *ListDocumentationVersionsBuilder[T]) build() string {
	query := listDocumentationVersions
	if len(b.conds) > 0 {
		if b.hasWhere {
			query += " AND " + strings.Join(b.conds, " AND ")
		} else {
			query += " WHERE " + strings.Join(b.conds, " AND ")
		}
	}
	if b.order != "" {
		query += " ORDER BY " + b.order
	}
	if b.limit != nil {
		b.args = append(b.args, *b.limit)
		if b.dollar {
			query += fmt.Sprintf(" LIMIT $%d", len(b.args))
		} else {
			query += " LIMIT ?"
		}
	}
	if b.offset != nil {
		b.args = append(b.args, *b.offset)
		if b.dollar {
			query += fmt.Sprintf(" OFFSET $%d", len(b.args))
		} else {
			query += " OFFSET ?"
		}
	}
	return query
}

func (b *ListDocumentationVersionsBuilder[T]) All() ([]T, error) {
	query := b.build()
	rows, err := b.q.db.Query(b.ctx, query, b.args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	for rows.Next() {
		item, err := narsilc.Scan[T](rows, []string{"id", "created_at", "updated_at", "slug", "label", "is_latest", "position", "published_nav_id"})
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentationVersionsByPosition = `-- name: ListDocumentationVersionsByPosition :many
SELECT id, created_at, updated_at, slug, label, is_latest, position, published_nav_id
FROM documentation_versions
ORDER BY position ASC, id ASC
`

// Lists versions by sidebar position.
func (q *Queries) ListDocumentationVersionsByPosition[T any](ctx context.Context) ([]T, error) {
	rows, err := q.db.Query(ctx, listDocumentationVersionsByPosition)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	for rows.Next() {
		item, err := narsilc.Scan[T](rows, []string{"id", "created_at", "updated_at", "slug", "label", "is_latest", "position", "published_nav_id"})
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentationVersion = `-- name: UpdateDocumentationVersion :one
UPDATE documentation_versions
SET
	updated_at = $2,
	slug = $3,
	label = $4,
	is_latest = $5,
	position = $6,
	published_nav_id = $7
WHERE id = $1
RETURNING id, created_at, updated_at, slug, label, is_latest, position, published_nav_id
`

type UpdateDocumentationVersionParams struct {
	ID             int64
	UpdatedAt      pgtype.Timestamptz
	Slug           string
	Label          string
	IsLatest       bool
	Position       int32
	PublishedNavID pgtype.Int8
}

// Updates one DocumentationVersion by primary key and returns the row.
func (q *Queries) UpdateDocumentationVersion[T any](ctx context.Context, arg UpdateDocumentationVersionParams) (T, error) {
	row := q.db.QueryRow(ctx, updateDocumentationVersion,
		arg.ID,
		arg.UpdatedAt,
		arg.Slug,
		arg.Label,
		arg.IsLatest,
		arg.Position,
		arg.PublishedNavID,
	)
	return narsilc.Scan[T](row, []string{"id", "created_at", "updated_at", "slug", "label", "is_latest", "position", "published_nav_id"})
}

const upsertDocumentationVersion = `-- name: UpsertDocumentationVersion :one
INSERT INTO documentation_versions (
	id,
	created_at,
	updated_at,
	slug,
	label,
	is_latest,
	position,
	published_nav_id
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8
)
ON CONFLICT (id) DO UPDATE SET
	updated_at = excluded.updated_at,
	slug = excluded.slug,
	label = excluded.label,
	is_latest = excluded.is_latest,
	position = excluded.position,
	published_nav_id = excluded.published_nav_id
RETURNING id, created_at, updated_at, slug, label, is_latest, position, published_nav_id
`

type UpsertDocumentationVersionParams struct {
	ID             int64
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
	Slug           string
	Label          string
	IsLatest       bool
	Position       int32
	PublishedNavID pgtype.Int8
}

// Inserts or updates one DocumentationVersion and returns the row.
func (q *Queries) UpsertDocumentationVersion[T any](ctx context.Context, arg UpsertDocumentationVersionParams) (T, error) {
	row := q.db.QueryRow(ctx, upsertDocumentationVersion,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Slug,
		arg.Label,
		arg.IsLatest,
		arg.Position,
		arg.PublishedNavID,
	)
	return narsilc.Scan[T](row, []string{"id", "created_at", "updated_at", "slug", "label", "is_latest", "position", "published_nav_id"})
}
