// Code generated by narsilc. DO NOT EDIT.
// source: documentation_page.sql

package queries

import (
	"context"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/mbvlabs/narsilc"
)

const countDocumentationPages = `-- name: CountDocumentationPages :one
SELECT count(*)
FROM documentation_pages
`

// Counts DocumentationPage rows.
func (q *Queries) CountDocumentationPages(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentationPages)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocumentationPage = `-- name: CreateDocumentationPage :one
INSERT INTO documentation_pages (
	created_at,
	updated_at,
	version_id,
	slug,
	published_revision_id
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5
)
RETURNING id, created_at, updated_at, version_id, slug, published_revision_id
`

type CreateDocumentationPageParams struct {
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	VersionID           int64
	Slug                string
	PublishedRevisionID pgtype.Int8
}

// Inserts one DocumentationPage and returns the row.
func (q *Queries) CreateDocumentationPage[T any](ctx context.Context, arg CreateDocumentationPageParams) (T, error) {
	row := q.db.QueryRow(ctx, createDocumentationPage,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.VersionID,
		arg.Slug,
		arg.PublishedRevisionID,
	)
	return narsilc.Scan[T](row, []string{"id", "created_at", "updated_at", "version_id", "slug", "published_revision_id"})
}

const deleteDocumentationPage = `-- name: DeleteDocumentationPage :exec
DELETE FROM documentation_pages
WHERE id = $1
`

// Deletes one DocumentationPage by primary key.
func (q *Queries) DeleteDocumentationPage(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDocumentationPage, id)
	return err
}

const getDocumentationPage = `-- name: GetDocumentationPage :one
SELECT id, created_at, updated_at, version_id, slug, published_revision_id
FROM documentation_pages
WHERE id = $1
LIMIT 1
`

// Fetches one DocumentationPage by primary key.
func (q *Queries) GetDocumentationPage[T any](ctx context.Context, id int64) (T, error) {
	row := q.db.QueryRow(ctx, getDocumentationPage, id)
	return narsilc.Scan[T](row, []string{"id", "created_at", "updated_at", "version_id", "slug", "published_revision_id"})
}

const getDocumentationPageByVersionSlug = `-- name: GetDocumentationPageByVersionSlug :one
SELECT id, created_at, updated_at, version_id, slug, published_revision_id
FROM documentation_pages
WHERE version_id = $1 AND slug = $2
LIMIT 1
`

type GetDocumentationPageByVersionSlugParams struct {
	VersionID int64
	Slug      string
}

func (q *Queries) GetDocumentationPageByVersionSlug[T any](ctx context.Context, arg GetDocumentationPageByVersionSlugParams) (T, error) {
	row := q.db.QueryRow(ctx, getDocumentationPageByVersionSlug, arg.VersionID, arg.Slug)
	return narsilc.Scan[T](row, []string{"id", "created_at", "updated_at", "version_id", "slug", "published_revision_id"})
}

const listDocumentationPages = `-- name: ListDocumentationPages :many
SELECT id, created_at, updated_at, version_id, slug, published_revision_id
FROM documentation_pages
`

// Lists DocumentationPage rows.

func (q *Queries) ListDocumentationPages[T any](ctx context.Context) *ListDocumentationPagesBuilder[T] {
	return &ListDocumentationPagesBuilder[T]{
		q:        q,
		ctx:      ctx,
		args:     []any{},
		hasWhere: false,
		dollar:   true,
	}
}

type ListDocumentationPagesBuilder[T any] struct {
	q        *Queries
	ctx      context.Context
	args     []any
	conds    []string
	order    string
	limit    *int32
	offset   *int32
	hasWhere bool
	dollar   bool
}

func (b *ListDocumentationPagesBuilder[T]) OrderByIDAsc() *ListDocumentationPagesBuilder[T] {
	b.order = `id ASC`
	return b
}

func (b *ListDocumentationPagesBuilder[T]) OrderByIDDesc() *ListDocumentationPagesBuilder[T] {
	b.order = `id DESC`
	return b
}

func (b *ListDocumentationPagesBuilder[T]) Limit(n int32) *ListDocumentationPagesBuilder[T] {
	b.limit = &n
	return b
}

func (b *ListDocumentationPagesBuilder[T]) Offset(n int32) *ListDocumentationPagesBuilder[T] {
	b.offset = &n
	return b
}

func (b *ListDocumentationPagesBuilder[T]) build() string {
	query := listDocumentationPages
	if len(b.conds) > 0 {
		if b.hasWhere {
			query += " AND " + strings.Join(b.conds, " AND ")
		} else {
			query += " WHERE " + strings.Join(b.conds, " AND ")
		}
	}
	if b.order != "" {
		query += " ORDER BY " + b.order
	}
	if b.limit != nil {
		b.args = append(b.args, *b.limit)
		if b.dollar {
			query += fmt.Sprintf(" LIMIT $%d", len(b.args))
		} else {
			query += " LIMIT ?"
		}
	}
	if b.offset != nil {
		b.args = append(b.args, *b.offset)
		if b.dollar {
			query += fmt.Sprintf(" OFFSET $%d", len(b.args))
		} else {
			query += " OFFSET ?"
		}
	}
	return query
}

func (b *ListDocumentationPagesBuilder[T]) All() ([]T, error) {
	query := b.build()
	rows, err := b.q.db.Query(b.ctx, query, b.args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	for rows.Next() {
		item, err := narsilc.Scan[T](rows, []string{"id", "created_at", "updated_at", "version_id", "slug", "published_revision_id"})
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentationPagesByVersion = `-- name: ListDocumentationPagesByVersion :many
SELECT id, created_at, updated_at, version_id, slug, published_revision_id
FROM documentation_pages
WHERE version_id = $1
ORDER BY id ASC
`

func (q *Queries) ListDocumentationPagesByVersion[T any](ctx context.Context, versionID int64) ([]T, error) {
	rows, err := q.db.Query(ctx, listDocumentationPagesByVersion, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	for rows.Next() {
		item, err := narsilc.Scan[T](rows, []string{"id", "created_at", "updated_at", "version_id", "slug", "published_revision_id"})
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentationPage = `-- name: UpdateDocumentationPage :one
UPDATE documentation_pages
SET
	updated_at = $2,
	version_id = $3,
	slug = $4,
	published_revision_id = $5
WHERE id = $1
RETURNING id, created_at, updated_at, version_id, slug, published_revision_id
`

type UpdateDocumentationPageParams struct {
	ID                  int64
	UpdatedAt           pgtype.Timestamptz
	VersionID           int64
	Slug                string
	PublishedRevisionID pgtype.Int8
}

// Updates one DocumentationPage by primary key and returns the row.
func (q *Queries) UpdateDocumentationPage[T any](ctx context.Context, arg UpdateDocumentationPageParams) (T, error) {
	row := q.db.QueryRow(ctx, updateDocumentationPage,
		arg.ID,
		arg.UpdatedAt,
		arg.VersionID,
		arg.Slug,
		arg.PublishedRevisionID,
	)
	return narsilc.Scan[T](row, []string{"id", "created_at", "updated_at", "version_id", "slug", "published_revision_id"})
}

const upsertDocumentationPage = `-- name: UpsertDocumentationPage :one
INSERT INTO documentation_pages (
	id,
	created_at,
	updated_at,
	version_id,
	slug,
	published_revision_id
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6
)
ON CONFLICT (id) DO UPDATE SET
	updated_at = excluded.updated_at,
	version_id = excluded.version_id,
	slug = excluded.slug,
	published_revision_id = excluded.published_revision_id
RETURNING id, created_at, updated_at, version_id, slug, published_revision_id
`

type UpsertDocumentationPageParams struct {
	ID                  int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	VersionID           int64
	Slug                string
	PublishedRevisionID pgtype.Int8
}

// Inserts or updates one DocumentationPage and returns the row.
func (q *Queries) UpsertDocumentationPage[T any](ctx context.Context, arg UpsertDocumentationPageParams) (T, error) {
	row := q.db.QueryRow(ctx, upsertDocumentationPage,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.VersionID,
		arg.Slug,
		arg.PublishedRevisionID,
	)
	return narsilc.Scan[T](row, []string{"id", "created_at", "updated_at", "version_id", "slug", "published_revision_id"})
}
