// Code generated by narsilc. DO NOT EDIT.
// source: documentation_nav_revision.sql

package queries

import (
	"context"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/mbvlabs/narsilc"
	"uuid"
)

const countDocumentationNavRevisions = `-- name: CountDocumentationNavRevisions :one
SELECT count(*)
FROM documentation_nav_revisions
`

// Counts DocumentationNavRevision rows.
func (q *Queries) CountDocumentationNavRevisions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentationNavRevisions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocumentationNavRevision = `-- name: CreateDocumentationNavRevision :one
INSERT INTO documentation_nav_revisions (
	created_at,
	version_id,
	status,
	tree,
	created_by,
	published_at
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6
)
RETURNING id, created_at, version_id, status, tree, created_by, published_at
`

type CreateDocumentationNavRevisionParams struct {
	CreatedAt   pgtype.Timestamptz
	VersionID   int64
	Status      string
	Tree        []byte
	CreatedBy   uuid.UUID
	PublishedAt pgtype.Timestamptz
}

// Inserts one DocumentationNavRevision and returns the row.
func (q *Queries) CreateDocumentationNavRevision[T any](ctx context.Context, arg CreateDocumentationNavRevisionParams) (T, error) {
	row := q.db.QueryRow(ctx, createDocumentationNavRevision,
		arg.CreatedAt,
		arg.VersionID,
		arg.Status,
		arg.Tree,
		arg.CreatedBy,
		arg.PublishedAt,
	)
	return narsilc.Scan[T](row, []string{"id", "created_at", "version_id", "status", "tree", "created_by", "published_at"})
}

const deleteDocumentationNavRevision = `-- name: DeleteDocumentationNavRevision :exec
DELETE FROM documentation_nav_revisions
WHERE id = $1
`

// Deletes one DocumentationNavRevision by primary key.
func (q *Queries) DeleteDocumentationNavRevision(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDocumentationNavRevision, id)
	return err
}

const getDocumentationNavRevision = `-- name: GetDocumentationNavRevision :one
SELECT id, created_at, version_id, status, tree, created_by, published_at
FROM documentation_nav_revisions
WHERE id = $1
LIMIT 1
`

// Fetches one DocumentationNavRevision by primary key.
func (q *Queries) GetDocumentationNavRevision[T any](ctx context.Context, id int64) (T, error) {
	row := q.db.QueryRow(ctx, getDocumentationNavRevision, id)
	return narsilc.Scan[T](row, []string{"id", "created_at", "version_id", "status", "tree", "created_by", "published_at"})
}

const getDocumentationNavRevisionDraftByVersion = `-- name: GetDocumentationNavRevisionDraftByVersion :one
SELECT id, created_at, version_id, status, tree, created_by, published_at
FROM documentation_nav_revisions
WHERE version_id = $1 AND status = 'draft'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetDocumentationNavRevisionDraftByVersion[T any](ctx context.Context, versionID int64) (T, error) {
	row := q.db.QueryRow(ctx, getDocumentationNavRevisionDraftByVersion, versionID)
	return narsilc.Scan[T](row, []string{"id", "created_at", "version_id", "status", "tree", "created_by", "published_at"})
}

const listDocumentationNavRevisions = `-- name: ListDocumentationNavRevisions :many
SELECT id, created_at, version_id, status, tree, created_by, published_at
FROM documentation_nav_revisions
`

// Lists DocumentationNavRevision rows.

func (q *Queries) ListDocumentationNavRevisions[T any](ctx context.Context) *ListDocumentationNavRevisionsBuilder[T] {
	return &ListDocumentationNavRevisionsBuilder[T]{
		q:        q,
		ctx:      ctx,
		args:     []any{},
		hasWhere: false,
		dollar:   true,
	}
}

type ListDocumentationNavRevisionsBuilder[T any] struct {
	q        *Queries
	ctx      context.Context
	args     []any
	conds    []string
	order    string
	limit    *int32
	offset   *int32
	hasWhere bool
	dollar   bool
}

func (b *ListDocumentationNavRevisionsBuilder[T]) OrderByIDAsc() *ListDocumentationNavRevisionsBuilder[T] {
	b.order = `id ASC`
	return b
}

func (b *ListDocumentationNavRevisionsBuilder[T]) OrderByIDDesc() *ListDocumentationNavRevisionsBuilder[T] {
	b.order = `id DESC`
	return b
}

func (b *ListDocumentationNavRevisionsBuilder[T]) Limit(n int32) *ListDocumentationNavRevisionsBuilder[T] {
	b.limit = &n
	return b
}

func (b *ListDocumentationNavRevisionsBuilder[T]) Offset(n int32) *ListDocumentationNavRevisionsBuilder[T] {
	b.offset = &n
	return b
}

func (b *ListDocumentationNavRevisionsBuilder[T]) build() string {
	query := listDocumentationNavRevisions
	if len(b.conds) > 0 {
		if b.hasWhere {
			query += " AND " + strings.Join(b.conds, " AND ")
		} else {
			query += " WHERE " + strings.Join(b.conds, " AND ")
		}
	}
	if b.order != "" {
		query += " ORDER BY " + b.order
	}
	if b.limit != nil {
		b.args = append(b.args, *b.limit)
		if b.dollar {
			query += fmt.Sprintf(" LIMIT $%d", len(b.args))
		} else {
			query += " LIMIT ?"
		}
	}
	if b.offset != nil {
		b.args = append(b.args, *b.offset)
		if b.dollar {
			query += fmt.Sprintf(" OFFSET $%d", len(b.args))
		} else {
			query += " OFFSET ?"
		}
	}
	return query
}

func (b *ListDocumentationNavRevisionsBuilder[T]) All() ([]T, error) {
	query := b.build()
	rows, err := b.q.db.Query(b.ctx, query, b.args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	for rows.Next() {
		item, err := narsilc.Scan[T](rows, []string{"id", "created_at", "version_id", "status", "tree", "created_by", "published_at"})
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentationNavRevisionsByVersion = `-- name: ListDocumentationNavRevisionsByVersion :many
SELECT id, created_at, version_id, status, tree, created_by, published_at
FROM documentation_nav_revisions
WHERE version_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDocumentationNavRevisionsByVersion[T any](ctx context.Context, versionID int64) ([]T, error) {
	rows, err := q.db.Query(ctx, listDocumentationNavRevisionsByVersion, versionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	for rows.Next() {
		item, err := narsilc.Scan[T](rows, []string{"id", "created_at", "version_id", "status", "tree", "created_by", "published_at"})
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentationNavRevision = `-- name: UpdateDocumentationNavRevision :one
UPDATE documentation_nav_revisions
SET
	version_id = $2,
	status = $3,
	tree = $4,
	created_by = $5,
	published_at = $6
WHERE id = $1
RETURNING id, created_at, version_id, status, tree, created_by, published_at
`

type UpdateDocumentationNavRevisionParams struct {
	ID          int64
	VersionID   int64
	Status      string
	Tree        []byte
	CreatedBy   uuid.UUID
	PublishedAt pgtype.Timestamptz
}

// Updates one DocumentationNavRevision by primary key and returns the row.
func (q *Queries) UpdateDocumentationNavRevision[T any](ctx context.Context, arg UpdateDocumentationNavRevisionParams) (T, error) {
	row := q.db.QueryRow(ctx, updateDocumentationNavRevision,
		arg.ID,
		arg.VersionID,
		arg.Status,
		arg.Tree,
		arg.CreatedBy,
		arg.PublishedAt,
	)
	return narsilc.Scan[T](row, []string{"id", "created_at", "version_id", "status", "tree", "created_by", "published_at"})
}

const upsertDocumentationNavRevision = `-- name: UpsertDocumentationNavRevision :one
INSERT INTO documentation_nav_revisions (
	id,
	created_at,
	version_id,
	status,
	tree,
	created_by,
	published_at
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7
)
ON CONFLICT (id) DO UPDATE SET
	version_id = excluded.version_id,
	status = excluded.status,
	tree = excluded.tree,
	created_by = excluded.created_by,
	published_at = excluded.published_at
RETURNING id, created_at, version_id, status, tree, created_by, published_at
`

type UpsertDocumentationNavRevisionParams struct {
	ID          int64
	CreatedAt   pgtype.Timestamptz
	VersionID   int64
	Status      string
	Tree        []byte
	CreatedBy   uuid.UUID
	PublishedAt pgtype.Timestamptz
}

// Inserts or updates one DocumentationNavRevision and returns the row.
func (q *Queries) UpsertDocumentationNavRevision[T any](ctx context.Context, arg UpsertDocumentationNavRevisionParams) (T, error) {
	row := q.db.QueryRow(ctx, upsertDocumentationNavRevision,
		arg.ID,
		arg.CreatedAt,
		arg.VersionID,
		arg.Status,
		arg.Tree,
		arg.CreatedBy,
		arg.PublishedAt,
	)
	return narsilc.Scan[T](row, []string{"id", "created_at", "version_id", "status", "tree", "created_by", "published_at"})
}
