// Code generated by narsilc. DO NOT EDIT.
// source: documentation_revision.sql

package queries

import (
	"context"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/mbvlabs/narsilc"
	"uuid"
)

const countDocumentationRevisions = `-- name: CountDocumentationRevisions :one
SELECT count(*)
FROM documentation_revisions
`

// Counts DocumentationRevision rows.
func (q *Queries) CountDocumentationRevisions(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countDocumentationRevisions)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createDocumentationRevision = `-- name: CreateDocumentationRevision :one
INSERT INTO documentation_revisions (
	created_at,
	page_id,
	status,
	title,
	meta_title,
	description,
	body_markdown,
	headings,
	created_by,
	published_at
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8,
	$9,
	$10
)
RETURNING id, created_at, page_id, status, title, description, body_markdown, headings, created_by, published_at, meta_title
`

type CreateDocumentationRevisionParams struct {
	CreatedAt    pgtype.Timestamptz
	PageID       int64
	Status       string
	Title        string
	MetaTitle    string
	Description  string
	BodyMarkdown string
	Headings     []byte
	CreatedBy    uuid.UUID
	PublishedAt  pgtype.Timestamptz
}

// Inserts one DocumentationRevision and returns the row.
func (q *Queries) CreateDocumentationRevision[T any](ctx context.Context, arg CreateDocumentationRevisionParams) (T, error) {
	row := q.db.QueryRow(ctx, createDocumentationRevision,
		arg.CreatedAt,
		arg.PageID,
		arg.Status,
		arg.Title,
		arg.MetaTitle,
		arg.Description,
		arg.BodyMarkdown,
		arg.Headings,
		arg.CreatedBy,
		arg.PublishedAt,
	)
	return narsilc.Scan[T](row, []string{"id", "created_at", "page_id", "status", "title", "description", "body_markdown", "headings", "created_by", "published_at", "meta_title"})
}

const deleteDocumentationRevision = `-- name: DeleteDocumentationRevision :exec
DELETE FROM documentation_revisions
WHERE id = $1
`

// Deletes one DocumentationRevision by primary key.
func (q *Queries) DeleteDocumentationRevision(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, deleteDocumentationRevision, id)
	return err
}

const getDocumentationRevision = `-- name: GetDocumentationRevision :one
SELECT id, created_at, page_id, status, title, description, body_markdown, headings, created_by, published_at, meta_title
FROM documentation_revisions
WHERE id = $1
LIMIT 1
`

// Fetches one DocumentationRevision by primary key.
func (q *Queries) GetDocumentationRevision[T any](ctx context.Context, id int64) (T, error) {
	row := q.db.QueryRow(ctx, getDocumentationRevision, id)
	return narsilc.Scan[T](row, []string{"id", "created_at", "page_id", "status", "title", "description", "body_markdown", "headings", "created_by", "published_at", "meta_title"})
}

const getDocumentationRevisionDraftByPage = `-- name: GetDocumentationRevisionDraftByPage :one
SELECT id, created_at, page_id, status, title, description, body_markdown, headings, created_by, published_at, meta_title
FROM documentation_revisions
WHERE page_id = $1 AND status = 'draft'
ORDER BY created_at DESC
LIMIT 1
`

func (q *Queries) GetDocumentationRevisionDraftByPage[T any](ctx context.Context, pageID int64) (T, error) {
	row := q.db.QueryRow(ctx, getDocumentationRevisionDraftByPage, pageID)
	return narsilc.Scan[T](row, []string{"id", "created_at", "page_id", "status", "title", "description", "body_markdown", "headings", "created_by", "published_at", "meta_title"})
}

const listDocumentationRevisions = `-- name: ListDocumentationRevisions :many
SELECT id, created_at, page_id, status, title, description, body_markdown, headings, created_by, published_at, meta_title
FROM documentation_revisions
`

// Lists DocumentationRevision rows.

func (q *Queries) ListDocumentationRevisions[T any](ctx context.Context) *ListDocumentationRevisionsBuilder[T] {
	return &ListDocumentationRevisionsBuilder[T]{
		q:        q,
		ctx:      ctx,
		args:     []any{},
		hasWhere: false,
		dollar:   true,
	}
}

type ListDocumentationRevisionsBuilder[T any] struct {
	q        *Queries
	ctx      context.Context
	args     []any
	conds    []string
	order    string
	limit    *int32
	offset   *int32
	hasWhere bool
	dollar   bool
}

func (b *ListDocumentationRevisionsBuilder[T]) OrderByIDAsc() *ListDocumentationRevisionsBuilder[T] {
	b.order = `id ASC`
	return b
}

func (b *ListDocumentationRevisionsBuilder[T]) OrderByIDDesc() *ListDocumentationRevisionsBuilder[T] {
	b.order = `id DESC`
	return b
}

func (b *ListDocumentationRevisionsBuilder[T]) Limit(n int32) *ListDocumentationRevisionsBuilder[T] {
	b.limit = &n
	return b
}

func (b *ListDocumentationRevisionsBuilder[T]) Offset(n int32) *ListDocumentationRevisionsBuilder[T] {
	b.offset = &n
	return b
}

func (b *ListDocumentationRevisionsBuilder[T]) build() string {
	query := listDocumentationRevisions
	if len(b.conds) > 0 {
		if b.hasWhere {
			query += " AND " + strings.Join(b.conds, " AND ")
		} else {
			query += " WHERE " + strings.Join(b.conds, " AND ")
		}
	}
	if b.order != "" {
		query += " ORDER BY " + b.order
	}
	if b.limit != nil {
		b.args = append(b.args, *b.limit)
		if b.dollar {
			query += fmt.Sprintf(" LIMIT $%d", len(b.args))
		} else {
			query += " LIMIT ?"
		}
	}
	if b.offset != nil {
		b.args = append(b.args, *b.offset)
		if b.dollar {
			query += fmt.Sprintf(" OFFSET $%d", len(b.args))
		} else {
			query += " OFFSET ?"
		}
	}
	return query
}

func (b *ListDocumentationRevisionsBuilder[T]) All() ([]T, error) {
	query := b.build()
	rows, err := b.q.db.Query(b.ctx, query, b.args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	for rows.Next() {
		item, err := narsilc.Scan[T](rows, []string{"id", "created_at", "page_id", "status", "title", "description", "body_markdown", "headings", "created_by", "published_at", "meta_title"})
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentationRevisionsByPage = `-- name: ListDocumentationRevisionsByPage :many
SELECT id, created_at, page_id, status, title, description, body_markdown, headings, created_by, published_at, meta_title
FROM documentation_revisions
WHERE page_id = $1
ORDER BY created_at DESC, id DESC
`

func (q *Queries) ListDocumentationRevisionsByPage[T any](ctx context.Context, pageID int64) ([]T, error) {
	rows, err := q.db.Query(ctx, listDocumentationRevisionsByPage, pageID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	for rows.Next() {
		item, err := narsilc.Scan[T](rows, []string{"id", "created_at", "page_id", "status", "title", "description", "body_markdown", "headings", "created_by", "published_at", "meta_title"})
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDocumentationRevision = `-- name: UpdateDocumentationRevision :one
UPDATE documentation_revisions
SET
	page_id = $2,
	status = $3,
	title = $4,
	meta_title = $5,
	description = $6,
	body_markdown = $7,
	headings = $8,
	created_by = $9,
	published_at = $10
WHERE id = $1
RETURNING id, created_at, page_id, status, title, description, body_markdown, headings, created_by, published_at, meta_title
`

type UpdateDocumentationRevisionParams struct {
	ID           int64
	PageID       int64
	Status       string
	Title        string
	MetaTitle    string
	Description  string
	BodyMarkdown string
	Headings     []byte
	CreatedBy    uuid.UUID
	PublishedAt  pgtype.Timestamptz
}

// Updates one DocumentationRevision by primary key and returns the row.
func (q *Queries) UpdateDocumentationRevision[T any](ctx context.Context, arg UpdateDocumentationRevisionParams) (T, error) {
	row := q.db.QueryRow(ctx, updateDocumentationRevision,
		arg.ID,
		arg.PageID,
		arg.Status,
		arg.Title,
		arg.MetaTitle,
		arg.Description,
		arg.BodyMarkdown,
		arg.Headings,
		arg.CreatedBy,
		arg.PublishedAt,
	)
	return narsilc.Scan[T](row, []string{"id", "created_at", "page_id", "status", "title", "description", "body_markdown", "headings", "created_by", "published_at", "meta_title"})
}

const upsertDocumentationRevision = `-- name: UpsertDocumentationRevision :one
INSERT INTO documentation_revisions (
	id,
	created_at,
	page_id,
	status,
	title,
	meta_title,
	description,
	body_markdown,
	headings,
	created_by,
	published_at
) VALUES (
	$1,
	$2,
	$3,
	$4,
	$5,
	$6,
	$7,
	$8,
	$9,
	$10,
	$11
)
ON CONFLICT (id) DO UPDATE SET
	page_id = excluded.page_id,
	status = excluded.status,
	title = excluded.title,
	meta_title = excluded.meta_title,
	description = excluded.description,
	body_markdown = excluded.body_markdown,
	headings = excluded.headings,
	created_by = excluded.created_by,
	published_at = excluded.published_at
RETURNING id, created_at, page_id, status, title, description, body_markdown, headings, created_by, published_at, meta_title
`

type UpsertDocumentationRevisionParams struct {
	ID           int64
	CreatedAt    pgtype.Timestamptz
	PageID       int64
	Status       string
	Title        string
	MetaTitle    string
	Description  string
	BodyMarkdown string
	Headings     []byte
	CreatedBy    uuid.UUID
	PublishedAt  pgtype.Timestamptz
}

// Inserts or updates one DocumentationRevision and returns the row.
func (q *Queries) UpsertDocumentationRevision[T any](ctx context.Context, arg UpsertDocumentationRevisionParams) (T, error) {
	row := q.db.QueryRow(ctx, upsertDocumentationRevision,
		arg.ID,
		arg.CreatedAt,
		arg.PageID,
		arg.Status,
		arg.Title,
		arg.MetaTitle,
		arg.Description,
		arg.BodyMarkdown,
		arg.Headings,
		arg.CreatedBy,
		arg.PublishedAt,
	)
	return narsilc.Scan[T](row, []string{"id", "created_at", "page_id", "status", "title", "description", "body_markdown", "headings", "created_by", "published_at", "meta_title"})
}
