// Code generated by narsilc. DO NOT EDIT.
// source: token.sql

package queries

import (
	"context"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/mbvlabs/narsilc"
	"uuid"
)

const countTokens = `-- name: CountTokens :one
SELECT count(*)
FROM tokens
`

func (q *Queries) CountTokens(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTokens)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (
	id,
	created_at,
	updated_at,
	scope,
	expires_at,
	hash,
	meta_data
) VALUES (
	$1, $2, $3, $4, $5, $6, $7
)
RETURNING id, created_at, updated_at, scope, expires_at, hash, meta_data
`

type CreateTokenParams struct {
	ID        uuid.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	Scope     string
	ExpiresAt pgtype.Timestamptz
	Hash      string
	MetaData  []byte
}

func (q *Queries) CreateToken[T any](ctx context.Context, arg CreateTokenParams) (T, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Scope,
		arg.ExpiresAt,
		arg.Hash,
		arg.MetaData,
	)
	return narsilc.Scan[T](row, []string{"id", "created_at", "updated_at", "scope", "expires_at", "hash", "meta_data"})
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM tokens
WHERE id = $1
`

func (q *Queries) DeleteToken(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteToken, id)
	return err
}

const getToken = `-- name: GetToken :one
SELECT id, created_at, updated_at, scope, expires_at, hash, meta_data
FROM tokens
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetToken[T any](ctx context.Context, id uuid.UUID) (T, error) {
	row := q.db.QueryRow(ctx, getToken, id)
	return narsilc.Scan[T](row, []string{"id", "created_at", "updated_at", "scope", "expires_at", "hash", "meta_data"})
}

const getTokenByScopeAndHash = `-- name: GetTokenByScopeAndHash :one
SELECT id, created_at, updated_at, scope, expires_at, hash, meta_data
FROM tokens
WHERE scope = $1
	AND hash = $2
LIMIT 1
`

type GetTokenByScopeAndHashParams struct {
	Scope string
	Hash  string
}

func (q *Queries) GetTokenByScopeAndHash[T any](ctx context.Context, arg GetTokenByScopeAndHashParams) (T, error) {
	row := q.db.QueryRow(ctx, getTokenByScopeAndHash, arg.Scope, arg.Hash)
	return narsilc.Scan[T](row, []string{"id", "created_at", "updated_at", "scope", "expires_at", "hash", "meta_data"})
}

const listTokens = `-- name: ListTokens :many
SELECT id, created_at, updated_at, scope, expires_at, hash, meta_data
FROM tokens
`

func (q *Queries) ListTokens[T any](ctx context.Context) *ListTokensBuilder[T] {
	return &ListTokensBuilder[T]{
		q:        q,
		ctx:      ctx,
		args:     []any{},
		hasWhere: false,
		dollar:   true,
	}
}

type ListTokensBuilder[T any] struct {
	q        *Queries
	ctx      context.Context
	args     []any
	conds    []string
	order    string
	limit    *int32
	offset   *int32
	hasWhere bool
	dollar   bool
}

func (b *ListTokensBuilder[T]) OrderByIDAsc() *ListTokensBuilder[T] {
	b.order = `id ASC`
	return b
}

func (b *ListTokensBuilder[T]) OrderByIDDesc() *ListTokensBuilder[T] {
	b.order = `id DESC`
	return b
}

func (b *ListTokensBuilder[T]) Limit(n int32) *ListTokensBuilder[T] {
	b.limit = &n
	return b
}

func (b *ListTokensBuilder[T]) Offset(n int32) *ListTokensBuilder[T] {
	b.offset = &n
	return b
}

func (b *ListTokensBuilder[T]) build() string {
	query := listTokens
	if len(b.conds) > 0 {
		if b.hasWhere {
			query += " AND " + strings.Join(b.conds, " AND ")
		} else {
			query += " WHERE " + strings.Join(b.conds, " AND ")
		}
	}
	if b.order != "" {
		query += " ORDER BY " + b.order
	}
	if b.limit != nil {
		b.args = append(b.args, *b.limit)
		if b.dollar {
			query += fmt.Sprintf(" LIMIT $%d", len(b.args))
		} else {
			query += " LIMIT ?"
		}
	}
	if b.offset != nil {
		b.args = append(b.args, *b.offset)
		if b.dollar {
			query += fmt.Sprintf(" OFFSET $%d", len(b.args))
		} else {
			query += " OFFSET ?"
		}
	}
	return query
}

func (b *ListTokensBuilder[T]) All() ([]T, error) {
	query := b.build()
	rows, err := b.q.db.Query(b.ctx, query, b.args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	for rows.Next() {
		item, err := narsilc.Scan[T](rows, []string{"id", "created_at", "updated_at", "scope", "expires_at", "hash", "meta_data"})
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
