// Code generated by narsilc. DO NOT EDIT.
// source: user.sql

package queries

import (
	"context"
	"fmt"
	"strings"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/mbvlabs/narsilc"
	"uuid"
)

const countUsers = `-- name: CountUsers :one
SELECT count(*)
FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
	id,
	created_at,
	updated_at,
	email,
	email_validated_at,
	password,
	is_admin
) VALUES (
	$1, $2, $3, $4, $5, $6, $7
)
RETURNING id, created_at, updated_at, email, email_validated_at, password, is_admin
`

type CreateUserParams struct {
	ID               uuid.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Email            string
	EmailValidatedAt pgtype.Timestamptz
	Password         []byte
	IsAdmin          bool
}

func (q *Queries) CreateUser[T any](ctx context.Context, arg CreateUserParams) (T, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.ID,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.Email,
		arg.EmailValidatedAt,
		arg.Password,
		arg.IsAdmin,
	)
	return narsilc.Scan[T](row, []string{"id", "created_at", "updated_at", "email", "email_validated_at", "password", "is_admin"})
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, created_at, updated_at, email, email_validated_at, password, is_admin
FROM users
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetUser[T any](ctx context.Context, id uuid.UUID) (T, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	return narsilc.Scan[T](row, []string{"id", "created_at", "updated_at", "email", "email_validated_at", "password", "is_admin"})
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, created_at, updated_at, email, email_validated_at, password, is_admin
FROM users
WHERE email = $1
LIMIT 1
`

func (q *Queries) GetUserByEmail[T any](ctx context.Context, email string) (T, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	return narsilc.Scan[T](row, []string{"id", "created_at", "updated_at", "email", "email_validated_at", "password", "is_admin"})
}

const listUsers = `-- name: ListUsers :many
SELECT id, created_at, updated_at, email, email_validated_at, password, is_admin
FROM users
`

func (q *Queries) ListUsers[T any](ctx context.Context) *ListUsersBuilder[T] {
	return &ListUsersBuilder[T]{
		q:        q,
		ctx:      ctx,
		args:     []any{},
		hasWhere: false,
		dollar:   true,
	}
}

type ListUsersBuilder[T any] struct {
	q        *Queries
	ctx      context.Context
	args     []any
	conds    []string
	order    string
	limit    *int32
	offset   *int32
	hasWhere bool
	dollar   bool
}

func (b *ListUsersBuilder[T]) OrderByIDAsc() *ListUsersBuilder[T] {
	b.order = `id ASC`
	return b
}

func (b *ListUsersBuilder[T]) OrderByIDDesc() *ListUsersBuilder[T] {
	b.order = `id DESC`
	return b
}

func (b *ListUsersBuilder[T]) Limit(n int32) *ListUsersBuilder[T] {
	b.limit = &n
	return b
}

func (b *ListUsersBuilder[T]) Offset(n int32) *ListUsersBuilder[T] {
	b.offset = &n
	return b
}

func (b *ListUsersBuilder[T]) build() string {
	query := listUsers
	if len(b.conds) > 0 {
		if b.hasWhere {
			query += " AND " + strings.Join(b.conds, " AND ")
		} else {
			query += " WHERE " + strings.Join(b.conds, " AND ")
		}
	}
	if b.order != "" {
		query += " ORDER BY " + b.order
	}
	if b.limit != nil {
		b.args = append(b.args, *b.limit)
		if b.dollar {
			query += fmt.Sprintf(" LIMIT $%d", len(b.args))
		} else {
			query += " LIMIT ?"
		}
	}
	if b.offset != nil {
		b.args = append(b.args, *b.offset)
		if b.dollar {
			query += fmt.Sprintf(" OFFSET $%d", len(b.args))
		} else {
			query += " OFFSET ?"
		}
	}
	return query
}

func (b *ListUsersBuilder[T]) All() ([]T, error) {
	query := b.build()
	rows, err := b.q.db.Query(b.ctx, query, b.args...)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []T
	for rows.Next() {
		item, err := narsilc.Scan[T](rows, []string{"id", "created_at", "updated_at", "email", "email_validated_at", "password", "is_admin"})
		if err != nil {
			return nil, err
		}
		items = append(items, item)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
	email = $2,
	email_validated_at = $3,
	password = $4,
	is_admin = $5,
	updated_at = $6
WHERE id = $1
RETURNING id, created_at, updated_at, email, email_validated_at, password, is_admin
`

type UpdateUserParams struct {
	ID               uuid.UUID
	Email            string
	EmailValidatedAt pgtype.Timestamptz
	Password         []byte
	IsAdmin          bool
	UpdatedAt        pgtype.Timestamptz
}

func (q *Queries) UpdateUser[T any](ctx context.Context, arg UpdateUserParams) (T, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.EmailValidatedAt,
		arg.Password,
		arg.IsAdmin,
		arg.UpdatedAt,
	)
	return narsilc.Scan[T](row, []string{"id", "created_at", "updated_at", "email", "email_validated_at", "password", "is_admin"})
}
